mybatis:
  mapper-locations: classpath:cn/humhahey/mapper/*.xml
  type-aliases-package: cn.humhahey.pojo
  type-handlers-package: cn.humhahey.typeHandler
logging:
  level:
    cn:
      humhahey:
        mapper: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 5000
      initial-size: 5
      default-transaction-isolation: 2
#  redis:
#    port: 6379
#    host: 127.0.0.1
#    password: 123456
#    timeout: 2000
#    jedis:
#      pool:
#        max-active: 10
#        min-idle: 5
#        max-idle: 10
#        max-wait: 2000

